In [2]:
### Numpy 
# 고성능 수치 계산을 위해서 제작된 파이썬 라이브러리
# 머신러닝 또는 딥러닝 알고리즘은 기본적으로 다차원 배열에 대한 계산으로 볼수 있음
# 또는 대량 데이터를 다룰 때에 빠른 계산 능력이 요구되어 사용되는 라이브러리 

# 생성된 Numpy확인 - Numpy의 핵심 객체(Ndarray) 

import numpy as np

temp = np.array([1,2,3])
print(temp)

# 토튜리얼 : https://numpy.org/doc/stable/user/quickstart.html   


[1 2 3]


[1, 2, 3]

In [6]:
# Numpy 기본 문법
data1 = [1,2,3]
data1  

data2 = [1,1,2,2,3,4]  

# np.array으로 배열로 변환하기 (파이썬은 array가 있다.하지만 list를 많이씀)
my_array = np.array(data1)     
print(my_array)  # [1 2 3]     ","없이 배열로 나온다.  
print(my_array.shape) # (3,)   갯수

my_array2 = np.array(data2)
print(my_array2)  # [1 1 2 2 3 4]
print(my_array2.shape) # (6,)

# shape는 크키를 확인하는 함수이다. len과 비슷함

## 리스트 선언 없이 바로 np.array로 사용
my_array3 = np.array([3,4,5,12])
print(my_array3.dtype)  # dtype은 데이터 사이즈를 알려준다. 

# data Types 참조 : https://numpy.org/devdocs/user/basic.types.html
#  


[1 2 3]
(3,)
[1 1 2 2 3 4]
(6,)
int64


In [9]:
### 2차원 배열
my_array4 = np.array([[2,4,6],[8,10,12],[14,18,16],[20,22,24]])
my_array4 
my_array4.shape # (4, 3) 4개의 다차원 배열과 길이 3개의 배열



(4, 3)

In [14]:
### 3차 배열
my_array5 = np.array([[[2,4],[6,5]],[[8,10],[20,22]]])
my_array5 

array([[[ 2,  4],
        [ 6,  5]],

       [[ 8, 10],
        [20, 22]]])

In [20]:
### numpy배열생성 및 둘러보기 
# Arrange : 기본 함수 중에 Range함수와 조금 유사하며, 더욱 쉽게 배열을 만들게함. 
arrange_array = np.arange(5)
print(arrange_array)

arrange_array2 = np.arange(1,9,3) # 1~9까지 [1,2,3,4,5,6,7,8]을 3을 더한값[1,4,7] 
print(arrange_array2) 
arrange_array2.dtype # dtype('int64')         

[0 1 2 3 4]
[1 4 7]


dtype('int64')

In [24]:
### Zeros, Ones 
# 할당하는 사이즈 배열에 0이나1을 더욱 쉽게 입력하는 함수 
zeros_arr = np.zeros((3,2))
print(zeros_arr)
print("Data Type is",zeros_arr.dtype) # Data Type is float64
print("Data Shape is",zeros_arr.shape) # Data Shape is (3, 2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type is float64
Data Shape is (3, 2)


In [25]:
ones_arr = np.ones((3,2),dtype="int32")
print(ones_arr)
print("Data Type is",ones_arr.dtype) # Data Type is float64
print("Data Shape is",ones_arr.shape) # Data Shape is (3, 2)

[[1 1]
 [1 1]
 [1 1]]
Data Type is int32
Data Shape is (3, 2)


In [45]:
## Reshape

after_reshape = ones_arr.reshape(3,2)
print(after_reshape) 
print("Data Shape is",after_reshape.shape)

## 항상 변경이 가능하지는 않다. 조건은 size가 동일해야한다. 
# ones_arr를 다른 사이즈로 변경해보세요. 
# after_reshape1=ones_arr.reshape(2,3,2)
# print(after_reshape1)  

# after_reshape2 = ones_arr.reshape(3,2,2)
# print(after_reshape2)

# after_reshape3 = ones_arr.reshape(2,2,3)
# print(after_reshape3)

### -1의 의미는? 차원을 자동으로 계산한다는 의미이다. 
after_reshape4 = ones_arr.reshape(3,-1)
print(after_reshape4)

[[1 1]
 [1 1]
 [1 1]]
Data Shape is (3, 2)
[[1 1]
 [1 1]
 [1 1]]


In [50]:
### Numpy인덱싱과 슬라이싱
my_array = np.arange(0,4)
print(my_array)
print("my_array의 1번째 요소, 즉 0번인 것은 :",my_array[0]) # my_array의 1번째 요소, 즉 0번인 것은 : 0
print("my_array[0:3] :",my_array[0:3]) # my_array[0:3] : [0 1 2]
print("my_array[0:] :",my_array[0:]) # my_array[0:] : [0 1 2 3]
print("my_array[:2] :",my_array[:2]) # my_array[:2] : [0 1]
print("my_array[:] :",my_array[:]) # my_array[:] : [0 1 2 3]
print("my_array[0:-1] :",my_array[0:-1]) # my_array[0:-1] : [0 1 2]

[0 1 2 3]
my_array의 1번째 요소, 즉 0번인 것은 : 0
my_array[0:3] : [0 1 2]
my_array[0:] : [0 1 2 3]
my_array[:2] : [0 1]
my_array[:] : [0 1 2 3]
my_array[0:-1] : [0 1 2]


In [54]:
my_array2 = np.array(
    [[2,4,6,8,10,12,14,16,18],
     [3,6,9,12,15,18,21,24,27],
     [4,8,12,16,20,24,28,32,36],
     [5,10,15,20,25,30,35,40,45]
    ])
print(my_array2)
print(my_array2.shape) # (4, 9) 
print(my_array2[0:2,0:2]) 
print(my_array2[1:3,:]) 

[[ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]]
(4, 9)
[[2 4]
 [3 6]]
[[ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]]


In [56]:
### Numpy 정렬 : sort(), argsort()

# np.sort() : 원본에 변화를 주지 않고, 복사본을 전달함           
height_arr = np.array([174,165,182,180,168])
sorted_height_arr = np.sort(height_arr) 
print("Height Matrix :",height_arr )
print("np.sort() Matrix :", sorted_height_arr)   # 오름차순

# 내림차순 정렬
desc_sorted_height_arr = np.sort(height_arr)[::-1]  ## [::-1]끝에서부터 하나씩 줄여가겠단 의미 
print("np.sort()[::1] :",desc_sorted_height_arr) 


Height Matrix : [174 165 182 180 168]
np.sort() Matrix : [165 168 174 180 182]
np.sort()[::1] : [182 180 174 168 165]


In [59]:
###argsort()
# numpy.argsort() 함수는 지정된 축을 따라 데이터 인덱스의 배열을 반환하도록 지정된 종류의 정렬을 사용해 입력 배열에서 간접 정렬을 수행함.

fives = np.array([10,5,15,30])
fives_order = fives.argsort() 
print("original data :", fives) 
print("argsort() :", fives_order) # argsort() : [1 0 2 3] 오름차순 인덱싱 값을 반환
print("Ascending :", fives[fives_order]) # Ascending : [ 5 10 15 30]

# 넘파이 튜토리알 : https://numpy.org/learn/
# numpy Broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html 

# 숙제 같은 크기의 두 배열에 대한 연산과 서로 크기가 다른 두 배열의 연산을 공부하세요.


original data : [10  5 15 30]
argsort() : [1 0 2 3]
Ascending : [ 5 10 15 30]
